'use client'
import Navigation from '@/components/shared/Navigation'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/shared/Footer'
import { Providers } from '@/lib/provider'
import AuthChecker from './authChecker'
import { ErrorBoundary } from 'react-error-boundary'
import ErrorHandler from '@/components/errors/ErrorHandler'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {

  return (
    
      <html lang="en">
        <body className={inter.className}>
          <ErrorBoundary FallbackComponent={ErrorHandler}>
            <Providers>
                <AuthChecker>
                  {children}
                </AuthChecker>
            </Providers>
          </ErrorBoundary>
        </body>
      </html>
   
  )
}
